/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class native_function_NativeClass */

#ifndef _Included_native_function_NativeClass
#define _Included_native_function_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     native_function_NativeClass
 * Method:    getMyString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_native_1function_NativeClass_getMyString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
